title: David HC
description: "A typography lover, web designer, and musician. Doing web design for 8 years with specialty in minimal design and web typography."
permalink: /:path/
url: "https://daavidhc.com"

# Defaults
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      permalink: /:title
